---
- name: Storage VPS configuration
  vars:
    apt_packages:
      - apt-transport-https
      - aptitude
      - ca-certificates
      - bind9-dnsutils
      - python3
      - python3-pip
      - rsync
      - sysstat
      - ufw
      - neovim
    containers:
      - oppenheimer
    install_cache_dir: /opt/install
    pip_packages:
      - docker
      - docker-compose
    reboot: false
    timezone: Australia/Melbourne
  hosts: all
  user: xiaket

  pre_tasks:
    - name: Load environment variables
      set_fact:
        RPC_PASS: '{{ lookup("env", "RPC_PASS") or "" }}'
        RPC_USER: '{{ lookup("env", "RPC_USER") or "" }}'

  tasks:
    - import_tasks: tasks/os.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/services.yml
