---
# run this as: `ansible-playbook -i 45.32.92.26, init.yml --user root --ask-pass -vvv`
- name: configure everything for personal vultr server.
  hosts: 173.249.201.20

  tasks:
  - name: create user group
    group:
      name: xiaket
      state: present

  - name: create user
    user:
      name: xiaket
      group: xiaket
      shell: /bin/bash
      state: present

  - name: add ssh key dir
    file:
      path: /home/xiaket/.ssh
      owner: xiaket
      group: xiaket
      mode: 0755
      state: directory

  - name: add ssh key file
    copy:
      content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPl+A5uZ36FJk4odVUz7txVjEUC3zRNUIL0ssSkDD5kk xiaket@KaiXia.local"
      dest: /home/xiaket/.ssh/authorized_keys
      owner: xiaket
      group: xiaket
      mode: 0600

  - name: add sudo package
    apt:
      name: sudo
      state: present
      update_cache: yes

  - name: add sudo config file
    copy:
      content: "xiaket ALL=(ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/xiaket
      owner: root
      group: root
      mode: 0400

  - name: Disable remote root login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no"

  - name: Disable password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

  - name: restart sshd
    service:
      name: sshd
      state: restarted
