#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [ -f ./.env ]
then
  source ./.env
fi
rm -f entrypoint.retry
export ANSIBLE_SSH_PIPELINING=1
exec ansible-playbook -i "$1", -vv entrypoint.yml || rm -f entrypoint.retry
#exec ansible-playbook --check -i "$1", -vv entrypoint.yml || rm -f entrypoint.retry
