# Service level configurations.
- name: create oppenheimer config dir
  file:
    path: /var/oppenheimer
    state: directory
  become: true

- name: generate config file for transmission
  template:
    src: settings.json
    dest: /var/oppenheimer/settings.json
  become: true
  when:
    - RPC_PASS != ""
    - RPC_USER != ""

- name: enable oppenheimer service
  systemd:
    name: docker-compose@oppenheimer
    enabled: true
    state: started
  become: true

- name: Auto restart Oppenheimer service
  cron:
    name: "Auto restart Oppenheimer service."
    minute: "15"
    hour: "3"
    job: "service docker-compose@oppenheimer restart"
  become: yes
