nginx:
  image: nginx:1.11.10-alpine
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /data/shipyard/static:/usr/share/nginx/html:ro
    - /data/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /data/etc/ssl/blog.xiaket.org.key:/etc/nginx/ssl/blog.xiaket.org.key:ro
    - /data/etc/ssl/blog.xiaket.org.crt:/etc/nginx/ssl/blog.xiaket.org.crt:ro
  restart: always
