version: "3.7"

services:
  transmission:
    build:
      context: .
    container_name: transmission
    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
    environment:
      - TRANSMISSION_WEB_HOME=/tmc/
    networks:
      - oppenheimer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /transmission/downloads:/transmission/downloads
      - /transmission/watch:/transmission/watch
      - /transmission/incomplete:/transmission/incomplete
      - /var/oppenheimer:/var/transmission-daemon
    restart: always

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    networks:
      - oppenheimer
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile


networks:
  oppenheimer:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
