transmission:
  image: xiaket/transmission:alpine-latest
  container_name: transmission
  env_file:
     - .env_admin
  ports:
    - "0.0.0.0:8443:8443"
    - "51413:51413/tcp"
    - "51413:51413/udp"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /data/var/lib/transmission/downloads:/transmission/downloads
    - /data/var/lib/transmission/incomplete:/transmission/incomplete
    - /data/var/lib/transmission/watch:/transmission/watch
    - /data/var/lib/transmission/config:/etc/transmission-daemon
    - /data/etc/transmission/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - /data/etc/ssl/torrent.xiaket.org.key:/etc/nginx/ssl/torrent.xiaket.org.key:ro
    - /data/etc/ssl/torrent.xiaket.org.crt:/etc/nginx/ssl/torrent.xiaket.org.crt:ro
  restart: always
