---
# run this as: `ansible-playbook -i 45.32.92.26, acme_sh.yml --user xiaket -vvv`
- name: configure ACME.sh on this server
  hosts: 45.32.92.26
  vars:
    pip_packages:
      - docker-compose
      - setuptools

  tasks:
  - name: clone acme.sh repo
    git:
      repo: https://github.com/Neilpang/acme.sh.git
      dest: /data/shipyard/acme
      update: yes

  - name: install acme
    shell: |
      ./acme.sh --install  \
      --home /data/var/lib/acme \
      --config-home /data/var/lib/acme/data \
      --certhome  /data/var/lib/acme/certs \
    args:
      chdir: /data/shipyard/acme
      creates: /data/var/lib/acme/data/account.conf
    register: acme_install
    become: true
